<!DOCTYPE html>  
<html lang="en">  
    <head>
        <meta charset="UTF-8">
        <title>Goldeneye</title>
        <link href="/css/style.css" rel="stylesheet">
    </head>

    <body>
        <h1 id="companyName">GoldenEye</h1>
        <div class = "card">
            <h2 class="titlePage"> INDEX </h2>
            <a class="btn" href="register"> Register New User </a>
        </div>
    </body>
</html>